import type { AppView } from "./WorkflowSidebar";
import type { FunctionDefinition } from "../model/types";
import type { Language } from "../model/i18n";
import { t } from "../model/i18n";

function M({ text, sub }: { text: string; sub?: string }) { return <span className="math-var">{text}{sub && <sub>{sub}</sub>}</span>; }
function MathLine({ children }: { children: React.ReactNode }) { return <div className="math-line doc-math-line">{children}</div>; }
function EqOhmic({ language }: { language: Language }) { return <MathLine><M text="V" /> <span>=</span> <M text="I" /><M text="R" /> <span className="math-note">{language === "zh" ? "同一个欧姆关系可写成电压降或支路电流" : "same Ohmic law can be voltage drop or branch current"}</span></MathLine>; }

function UsageGuide({ language }: { language: Language }) {
  if (language === "zh") return <div className="doc-grid">
    <section className="card doc-card wide-card"><h2>快速开始：拟合一条 trace</h2><ol className="doc-steps"><li><strong>导入数据。</strong> 支持普通 V/I CSV，也支持 HappyMeasure 导出的单条或多条曲线文件。软件默认空白启动，避免误拟合示例数据。</li><li><strong>选择 trace。</strong> 多 trace 文件会变成下拉框中的多条 trace；当前版本一次只拟合下拉框选中的 trace。</li><li><strong>检查列和符号。</strong> 在数据卡片里确认电压列、电流列和点数。</li><li><strong>先用最小模型。</strong> 先从 D1 + Rs + Rsh 这类基本模型开始，残差说明需要时再加经验支路。</li><li><strong>设置初值和边界。</strong> 每个组件的“初值”按钮里可以设置初始值、上下界、是否参与拟合。</li><li><strong>看 warning 再报告。</strong> 绿色只代表数值质量门控通过，不代表物理模型唯一或一定正确。</li></ol></section>
    <section className="card doc-card"><h2>HappyMeasure 多 trace 导入</h2><p>导入后每条曲线会进入同一个下拉框；当前只拟合你选中的那一条。</p><details><summary>技术细节</summary><p>兼容 single-v2、combined wide-v2、combined long-v2。</p></details></section>
    <section className="card doc-card"><h2>当前到底拟合什么？</h2><p>只拟合下拉框当前选中的 trace。其他 trace 不进入 residual、不参与参数优化，也不会进入报告。</p></section>
    <section className="card doc-card"><h2>安全工作流</h2><p>不要一开始启用所有分支。先缩小电压范围、拟合简单模型、看残差，再逐步扩大范围和增加组件。</p></section>
  </div>;
  return <div className="doc-grid">
    <section className="card doc-card wide-card"><h2>Quick start: fitting one trace</h2><ol className="doc-steps"><li><strong>Import data.</strong> Use a plain V/I CSV or a single-/multi-trace HappyMeasure export. The app starts empty on purpose.</li><li><strong>Select the trace.</strong> Multi-trace files create one dropdown entry per trace; only the selected trace is fitted.</li><li><strong>Check sign and units.</strong> Confirm the selected voltage/current columns and point count.</li><li><strong>Choose the smallest model first.</strong> Start with D1 + Rs + Rsh, then add empirical branches only when residuals justify them.</li><li><strong>Set initials and bounds.</strong> Open Initials for each component.</li><li><strong>Run fit and read warnings.</strong> Green status is a numerical gate, not proof of model uniqueness.</li></ol></section>
    <section className="card doc-card"><h2>HappyMeasure multi-trace import</h2><p>Imported curves appear in one dropdown. Only the selected curve is fitted.</p><details><summary>Technical details</summary><p>Compatible wrappers: single-v2, combined wide-v2, combined long-v2.</p></details></section>
    <section className="card doc-card"><h2>What is fitted?</h2><p>Only the selected trace is fitted. Other traces are not included in residuals, optimization, or reports.</p></section>
    <section className="card doc-card"><h2>Safe workflow</h2><p>Use a narrow voltage range and a minimal model first. Expand only after residuals and warnings are acceptable.</p></section>
  </div>;
}

function FunctionGuide({ registry, language }: { registry: FunctionDefinition[]; language: Language }) {
  const lawGroups = registry.reduce<Record<string, FunctionDefinition[]>>((acc, item) => { (acc[item.law_id] ||= []).push(item); return acc; }, {});
  return <div className="doc-grid">
    <section className="card doc-card wide-card"><h2>{language === "zh" ? "函数说明：数学关系、计算形式、电路位置" : "Function guide: laws, forms, placements"}</h2><p>{language === "zh" ? "函数首先是数学关系，不天然属于串联或并联。一个组件实例再选择计算形式和电路位置。" : "A function is a mathematical law first. It is not intrinsically series or parallel; the component instance chooses form and placement."}</p><EqOhmic language={language}/><p><strong>{language === "zh" ? "例子：" : "Example:"}</strong> {language === "zh" ? "Rs 和 Rsh 都是欧姆关系。Rs 作为主路电压降；Rsh 作为结点支路电流。" : "Rs and Rsh are both Ohmic law. Rs is a main-path voltage drop; Rsh is a junction branch current."}</p></section>
    {registry.length === 0 ? <section className="card doc-card"><p className="muted">{language === "zh" ? "函数库还没有加载。" : "Registry not loaded yet."}</p></section> : Object.entries(lawGroups).map(([law, items]) => <section className="card doc-card" key={law}><h2>{items[0].law_name}</h2><p>{items[0].help_text}</p><p><strong>{language === "zh" ? "参数：" : "Parameters:"}</strong> {Array.from(new Set(items.flatMap((i) => i.parameters.map((p) => `${p.name}${p.unit ? ` (${p.unit})` : ""}`)))).join(", ")}</p><details><summary>{language === "zh" ? "高级/开发者信息" : "Advanced / developer details"}</summary><p className="muted">law_id: <code>{law}</code></p><p><strong>{language === "zh" ? "形式：" : "Forms:"}</strong> {Array.from(new Set(items.flatMap((i) => i.available_forms))).join(" / ")}</p><p><strong>{language === "zh" ? "位置：" : "Placements:"}</strong> {Array.from(new Set(items.flatMap((i) => i.allowed_placements))).join(" / ")}</p><p><strong>{language === "zh" ? "可执行适配器：" : "Executable adapters:"}</strong> {items.map((i) => `${i.function_type} (${i.display_name})`).join("; ")}</p></details></section>)}
  </div>;
}

function FittingLogic({ language }: { language: Language }) {
  return <div className="doc-grid">
    <section className="card doc-card wide-card"><h2>{language === "zh" ? "当前模型如何变成等效电路" : "How the selected model becomes a circuit"}</h2><p>{language === "zh" ? "模型构建器里的组件会按位置分到主路或结点支路。主路项先消耗电压；结点支路在剩余电压下产生电流。" : "Model-builder components are assigned to the main path or junction branches. Main-path terms consume voltage first; branches generate current at the remaining voltage."}</p></section>
    <section className="card doc-card wide-card"><h2>{language === "zh" ? "D1 + Rs + Rsh 的实际数学逻辑" : "Actual math for D1 + Rs + Rsh"}</h2><div className="stacked-math"><MathLine><M text="V" sub={language === "zh" ? "结点" : "junction"} /> <span>=</span> <M text="V" sub={language === "zh" ? "外部" : "external"} /> <span>−</span> <M text="I" /><M text="R" sub="s" /></MathLine><MathLine><M text="I" sub="D1" /> <span>=</span> <M text="I" sub="0" /> <span>[ exp(</span><M text="V" sub={language === "zh" ? "结点" : "junction"} /><span> / </span><M text="nV" sub="T" /><span>) − 1 ]</span></MathLine><MathLine><M text="I" sub="Rsh" /> <span>=</span> <M text="V" sub={language === "zh" ? "结点" : "junction"} /><span> / </span><M text="R" sub="sh" /></MathLine><MathLine><M text="I" sub={language === "zh" ? "端口" : "terminal"} /> <span>=</span> <M text="I" sub="D1" /> <span>+</span> <M text="I" sub="Rsh" /></MathLine></div></section>
    <section className="card doc-card"><h2>{language === "zh" ? "Rs 和 Rsh 的区别" : "Difference between Rs and Rsh"}</h2><p>{language === "zh" ? "二者都是欧姆关系。Rs 放在主路，用电压降形式；Rsh 放在支路，用电流形式。" : "Both are Ohmic. Rs is placed in the main path and evaluated as a voltage drop; Rsh is placed in a branch and evaluated as current."}</p></section>
    <section className="card doc-card"><h2>{language === "zh" ? "传统复合求解器 vs graph_dc" : "Legacy composite vs graph_dc"}</h2><p>{language === "zh" ? "legacy_composite 使用单结点隐式公式。graph_dc 会从图结构组装 DC 方程，目前仍是实验性功能，报告前必须交叉检查。" : "legacy_composite uses the one-junction implicit formula. graph_dc assembles DC equations from the topology graph and remains experimental."}</p></section>
  </div>;
}

function ConvergenceGuide({ language }: { language: Language }) {
  const steps = language === "zh" ? ["选择一条 trace：多 trace 文件只取下拉框当前选中的 trace 进入拟合。", "筛选电压范围：V min 和 V max 作用在外部电压上。", "可选排除平台/异常点：优化前移除疑似高电流平台点。", "打包自由参数：只有勾选 Fit? 的参数会变化。", "预测电流：求解器对每个外部电压点计算模型电流。", "计算残差：根据权重和 residual floor 计算目标函数。", "优化：least_squares 在上下界内寻找局部最小。", "质量门控：最终曲线、RMSE 和有限性检查通过后才显示绿色。"] : ["Select one trace: multi-trace imports are reduced to the selected trace before fitting.", "Filter voltage range: V min and V max are applied to external voltage.", "Optionally exclude plateaus/outliers before optimization.", "Pack only parameters with Fit? enabled.", "Predict current for each external voltage.", "Compute residuals using the selected weighting and residual floor.", "Optimize with least_squares inside bounds.", "Gate the final result before green success is allowed."];
  return <div className="doc-grid"><section className="card doc-card wide-card"><h2>{language === "zh" ? "拟合与收敛：代码里的实际流程" : "Fit & convergence: actual numerical logic"}</h2><ol className="doc-steps">{steps.map((s) => <li key={s}>{s}</li>)}</ol></section><section className="card doc-card"><h2>{language === "zh" ? "为什么收敛不等于物理正确" : "Why convergence is not proof"}</h2><p>{language === "zh" ? "收敛只说明优化器找到了当前目标函数的局部最小，不证明组件唯一、必要或物理真实。" : "Convergence means a local numerical minimum was found. It does not prove uniqueness, necessity, or physical reality."}</p></section><section className="card doc-card"><h2>{language === "zh" ? "坏收敛迹象" : "Bad convergence signs"}</h2><ul className="doc-steps"><li>{language === "zh" ? "红色状态或质量门控失败。" : "Red status or failed quality gate."}</li><li>{language === "zh" ? "参数卡在上下界。" : "Parameters stuck at bounds."}</li><li>{language === "zh" ? "不同初值得到不同参数但误差接近。" : "Different initials give different parameters with similar error."}</li><li>{language === "zh" ? "残差有明显系统结构。" : "Residuals show systematic structure."}</li></ul></section></div>;
}

export function UserDocumentationPage({ view, registry, appVersion, language = "en" }: { view: AppView; registry: FunctionDefinition[]; appVersion: string; language?: Language }) {
  const title = view === "usage" ? t(language, "titleUsage") : view === "functions" ? t(language, "titleFunctions") : view === "logic" ? t(language, "titleLogic") : t(language, "titleConvergence");
  return <div className="doc-page"><div className="card doc-hero"><div><h2>{title}</h2><p className="muted">{t(language, "docsHero")} v{appVersion}</p></div></div>{view === "usage" && <UsageGuide language={language} />}{view === "functions" && <FunctionGuide registry={registry} language={language} />}{view === "logic" && <FittingLogic language={language} />}{view === "convergence" && <ConvergenceGuide language={language} />}</div>;
}
