import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from "react";
import { Background, Controls, Panel, ReactFlow, useReactFlow } from "@xyflow/react";
import type { FunctionDefinition, ModelSpec } from "../../model/types";
import type { Language } from "../../model/i18n";
import type { BuilderBucket } from "../../model-builder/rules";
import { addDefinitionToModel, applyNicknameToParams } from "../../model-builder/mutations";
import { applyCustomExpressionParameterUnits, createComponentInLocation, removeComponent, updateComponent } from "../../model/utils";
import {
  addPolarityFor,
  addableDefinitionForBucket,
  definitionsForBucket,
  findComponentRef,
  firstComponentId,
} from "./modelHelpers";
import { ModelFlowContextProvider, type ModelFlowContextValue } from "./flowContext";
import { nodeTypes } from "./flowNodes";
import { edgeTypes } from "./ButtonEdge";
import { buildFlowGraph } from "./modelFlowGraph";
import { ModelPresetControls } from "./PresetControls";
import { ComponentCanvasEditor } from "./ComponentCanvasEditor";


export function ModelFlowCanvas({ model, registry, selectedId, setSelectedId, selectedDefinitions, setSelectedDefinitions, onChange, language, disabled, onGoToFitting, readOnly = false, previewContent, canvasActions }: {
  model: ModelSpec;
  registry: FunctionDefinition[];
  selectedId: string | null;
  setSelectedId: (id: string | null) => void;
  selectedDefinitions: Record<string, string>;
  setSelectedDefinitions: (patch: (current: Record<string, string>) => Record<string, string>) => void;
  onChange: (model: ModelSpec) => void;
  language: Language;
  disabled?: boolean;
  onGoToFitting?: () => void;
  readOnly?: boolean;
  previewContent?: ReactNode;
  canvasActions?: ReactNode;
}) {
  void previewContent;
  const { fitView } = useReactFlow();
  const [editorOffset, setEditorOffset] = useState({ x: 0, y: 0 });
  const editorDragRef = useRef<{ startX: number; startY: number; baseX: number; baseY: number } | null>(null);

  function defaultCustomNicknameFor(bucket: BuilderBucket) {
    return bucket === "main" ? "custom" : "custom";
  }

  function looksAutoGeneratedName(compId: string, value: string | null) {
    const name = (value ?? compId).trim();
    return /^(D\d+|Rs|Rsh|Barrier\d+|Softplus\d+|Ibias\(V\)|Iph)$/i.test(name);
  }

  const beginEditorDrag = useCallback((event: ReactPointerEvent) => {
    if (readOnly) return;
    event.preventDefault();
    event.stopPropagation();
    editorDragRef.current = { startX: event.clientX, startY: event.clientY, baseX: editorOffset.x, baseY: editorOffset.y };
    const move = (moveEvent: PointerEvent) => {
      const drag = editorDragRef.current;
      if (!drag) return;
      const x = Math.min(80, Math.max(-420, drag.baseX + moveEvent.clientX - drag.startX));
      const y = Math.min(420, Math.max(-80, drag.baseY + moveEvent.clientY - drag.startY));
      setEditorOffset({ x, y });
    };
    const up = () => {
      editorDragRef.current = null;
      window.removeEventListener("pointermove", move);
      window.removeEventListener("pointerup", up);
    };
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", up, { once: true });
  }, [editorOffset.x, editorOffset.y, readOnly]);

  const selectFirst = useCallback((next: ModelSpec) => {
    setSelectedId(firstComponentId(next));
  }, [setSelectedId]);

  const setAddDefinition = useCallback((bucket: BuilderBucket, functionType: string) => {
    setSelectedDefinitions((current) => ({ ...current, [bucket]: functionType }));
  }, [setSelectedDefinitions]);

  const addFrom = useCallback((bucket: BuilderBucket, functionType?: string) => {
    if (readOnly || disabled) return;
    const definitions = definitionsForBucket(registry, bucket);
    const definition = functionType
      ? definitions.find((item) => item.function_type === functionType)
      : addableDefinitionForBucket(model, definitions, bucket, selectedDefinitions[bucket]);
    if (!definition) return;
    const result = addDefinitionToModel(model, bucket, definition, addPolarityFor(model, bucket, definition));
    if (!result.added) return;
    onChange(result.model);
    setSelectedId(result.component.id);
  }, [disabled, model, onChange, readOnly, registry, selectedDefinitions, setSelectedId]);

  const removeById = useCallback((componentId: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const next = removeComponent(model, ref.location, ref.comp.id);
    onChange(next);
    setSelectedId(firstComponentId(next));
  }, [disabled, model, onChange, readOnly, setSelectedId]);

  const renameById = useCallback((componentId: string, nextName: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    const cleanName = nextName.trim();
    if (!ref || !cleanName) return;
    const nextComponent = applyNicknameToParams(ref.comp, cleanName);
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const replaceDefinitionById = useCallback((componentId: string, functionType: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const bucket = ref.comp.location === "series" ? "main" : "branches";
    const definition = definitionsForBucket(registry, bucket).find((item) => item.function_type === functionType);
    if (!definition) return;
    const replacement = createComponentInLocation(definition, ref.location, addPolarityFor(model, bucket, definition));
    const prevNick = typeof ref.comp.metadata?.nickname === "string" ? ref.comp.metadata.nickname : null;
    const switchingToCustom = definition.function_type === "custom" || definition.law_id === "custom_expression";
    const nick = switchingToCustom && looksAutoGeneratedName(ref.comp.id, prevNick)
      ? defaultCustomNicknameFor(bucket)
      : (prevNick ?? ref.comp.id);
    const renamed = applyCustomExpressionParameterUnits(applyNicknameToParams({
      ...replacement,
      id: ref.comp.id,
      location: ref.location,
      metadata: { ...(replacement.metadata ?? {}), nickname: nick },
    }, nick));
    onChange(updateComponent(model, ref.location, ref.comp.id, renamed));
  }, [disabled, model, onChange, readOnly, registry]);

  const updateExpressionById = useCallback((componentId: string, expression: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const nextComponent = applyCustomExpressionParameterUnits({
      ...ref.comp,
      metadata: { ...(ref.comp.metadata ?? {}), expression, expressionSource: "user" },
    }, expression);
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const updatePolarityById = useCallback((componentId: string, polarity: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const nextComponent = {
      ...ref.comp,
      polarity: polarity as "forward" | "reverse" | "symmetric" | null,
    };
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const graph = useMemo(() => buildFlowGraph(model, selectedId, language, {
    readOnly,
    disabled,
    registry,
  }), [model, selectedId, language, readOnly, disabled, registry]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      fitView({ padding: readOnly ? 0.22 : 0.22, duration: 180, maxZoom: readOnly ? 1.0 : 1.08 });
    }, readOnly ? 60 : 80);
    return () => window.clearTimeout(timer);
  }, [fitView, graph.nodes.length, graph.edges.length, readOnly]);

  const contextValue = useMemo<ModelFlowContextValue>(() => ({
    model,
    registry,
    language,
    disabled,
    readOnly,
    selectedDefinitions,
    removeById,
    addFrom,
    setAddDefinition,
    renameById,
    replaceDefinitionById,
    updateExpressionById,
    updatePolarityById,
  }), [addFrom, disabled, language, model, readOnly, registry, removeById, renameById, replaceDefinitionById, updateExpressionById, updatePolarityById, selectedDefinitions, setAddDefinition]);

  return <ModelFlowContextProvider value={contextValue}>
    <div className={`xy-model-workspace ${readOnly ? "xy-model-readonly" : ""}`} data-testid="equivalent-circuit-canvas">
      <div className="xy-model-flow-shell">
        <ReactFlow
          nodes={graph.nodes}
          edges={graph.edges}
          nodeTypes={nodeTypes}
          edgeTypes={edgeTypes}
          defaultEdgeOptions={{ type: "smoothstep", style: { strokeWidth: 2.4, stroke: "#111827" } }}
          fitView={readOnly}
          fitViewOptions={{ padding: 0.22, maxZoom: 1.0 }}
          defaultViewport={readOnly ? undefined : { x: 140, y: 80, zoom: 1 }}
          minZoom={readOnly ? 0.45 : 0.45}
          maxZoom={readOnly ? 1.4 : 2.4}
          nodesDraggable={false}
          nodesConnectable={false}
          edgesFocusable={false}
          edgesReconnectable={false}
          deleteKeyCode={null}
          connectOnClick={false}
          panOnScroll={false}
          zoomOnScroll={!readOnly}
          zoomOnPinch={!readOnly}
          zoomOnDoubleClick={!readOnly}
          attributionPosition="bottom-left"
          proOptions={{ hideAttribution: true }}
          onNodeClick={(_, node) => {
            if (readOnly) return;
            const refItem = node.data.refItem;
            if (refItem) setSelectedId(refItem.comp.id);
          }}
          onPaneClick={() => {
            if (!readOnly) setSelectedId(null);
          }}
        >
          <Background gap={24} size={1.4} />
          {!readOnly ? <Controls showInteractive={false} /> : null}
          {!readOnly ? <Panel position="top-left" className="xy-canvas-preset-panel">
            <ModelPresetControls model={model} language={language} onChange={onChange} disabled={disabled} onAfterPreset={selectFirst} onGoToFitting={onGoToFitting} />
            {canvasActions ? <div className="xy-canvas-synthetic-tool">{canvasActions}</div> : null}
          </Panel> : null}
          {!readOnly && selectedId ? <Panel position="top-right" className="xy-canvas-editor-panel">
            <div className="xy-draggable-editor-shell" style={{ transform: `translate(${editorOffset.x}px, ${editorOffset.y}px)` }}>
              <ComponentCanvasEditor selectedId={selectedId} onHeaderPointerDown={beginEditorDrag} />
            </div>
          </Panel> : null}

        </ReactFlow>
      </div>
    </div>
  </ModelFlowContextProvider>;
}
