import { useCallback, useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type ReactNode } from "react";
import { Background, Controls, Panel, ReactFlow, useReactFlow } from "@xyflow/react";
import type { FunctionDefinition, ModelSpec, ParameterSpec } from "../../model/types";
import type { Language } from "../../model/i18n";
import type { BuilderBucket } from "../../model-builder/rules";
import { applyNicknameToParams, buildPendingComponent } from "../../model-builder/mutations";
import { applyCustomExpressionParameterUnits, createComponentInLocation, removeComponent, updateComponent } from "../../model/utils";
import {
  addPolarityFor,
  addableDefinitionForBucket,
  definitionsForBucket,
  findComponentRef,
  firstComponentId,
} from "./modelHelpers";
import { ModelFlowContextProvider, parameterFromPatch, type AddPlacement, type ModelFlowContextValue } from "./flowContext";
import { nodeTypes } from "./flowNodes";
import { edgeTypes } from "./ButtonEdge";
import { buildFlowGraph, buildFlowGraphWithElk } from "./modelFlowGraph";
import { ModelPresetControls } from "./PresetControls";
import { ComponentCanvasEditor } from "./ComponentCanvasEditor";
import type { ComponentBehaviorMode, CustomParameterPatch } from "./types";

function getComponentOrder(comp: { metadata?: Record<string, unknown> }, fallback: number) {
  const raw = comp.metadata?.pathOrder;
  return typeof raw === "number" && Number.isFinite(raw) ? raw : fallback;
}

function withPathMetadata(component: ReturnType<typeof buildPendingComponent>, pathId: string, order: number) {
  return {
    ...component,
    metadata: {
      ...(component.metadata ?? {}),
      pathId,
      pathOrder: order,
    },
  };
}

function normalizePathOrders(model: ModelSpec, pathId: string, insertIndex: number) {
  const patch = <T extends keyof Pick<ModelSpec, "core" | "series" | "parallel">>(location: T) => model[location].map((comp, index) => {
    const compPath = typeof comp.metadata?.pathId === "string" ? comp.metadata.pathId : (comp.location === "series" ? "path:main" : `path:${comp.id}`);
    if (compPath !== pathId) return comp;
    const order = getComponentOrder(comp, index);
    return {
      ...comp,
      metadata: {
        ...(comp.metadata ?? {}),
        pathId,
        pathOrder: order >= insertIndex ? order + 1 : order,
      },
    };
  });
  return { ...model, core: patch("core"), series: patch("series"), parallel: patch("parallel") };
}

function defaultExpressionForBehavior(behavior: ComponentBehaviorMode) {
  if (behavior === "R_of_V") return "R0";
  if (behavior === "I_of_V") return "V / R0";
  if (behavior === "dV_of_I") return "I * R0";
  return "I - V / R0";
}

function defaultParameterFor(name: string): ParameterSpec {
  return { value: name.toLowerCase().startsWith("r") ? 1 : 1, lower: null, upper: null, fit: true, unit: null, label: name, description: "User-defined fitting parameter." };
}


export function ModelFlowCanvas({ model, registry, selectedId, setSelectedId, selectedDefinitions, setSelectedDefinitions, onChange, language, disabled, onGoToFitting, readOnly = false, previewContent, canvasActions }: {
  model: ModelSpec;
  registry: FunctionDefinition[];
  selectedId: string | null;
  setSelectedId: (id: string | null) => void;
  selectedDefinitions: Record<string, string>;
  setSelectedDefinitions: (patch: (current: Record<string, string>) => Record<string, string>) => void;
  onChange: (model: ModelSpec) => void;
  language: Language;
  disabled?: boolean;
  onGoToFitting?: () => void;
  readOnly?: boolean;
  previewContent?: ReactNode;
  canvasActions?: ReactNode;
}) {
  void previewContent;
  const { fitView } = useReactFlow();
  const [editorOffset, setEditorOffset] = useState({ x: 0, y: 0 });
  const editorDragRef = useRef<{ startX: number; startY: number; baseX: number; baseY: number } | null>(null);

  function defaultCustomNicknameFor(bucket: BuilderBucket) {
    return bucket === "main" ? "custom" : "custom";
  }

  function looksAutoGeneratedName(compId: string, value: string | null) {
    const name = (value ?? compId).trim();
    return /^(D\d+|Rs|Rsh|Barrier\d+|Softplus\d+|Ibias\(V\)|Iph)$/i.test(name);
  }

  const beginEditorDrag = useCallback((event: ReactPointerEvent) => {
    if (readOnly) return;
    event.preventDefault();
    event.stopPropagation();
    editorDragRef.current = { startX: event.clientX, startY: event.clientY, baseX: editorOffset.x, baseY: editorOffset.y };
    const move = (moveEvent: PointerEvent) => {
      const drag = editorDragRef.current;
      if (!drag) return;
      const x = Math.min(80, Math.max(-420, drag.baseX + moveEvent.clientX - drag.startX));
      const y = Math.min(420, Math.max(-80, drag.baseY + moveEvent.clientY - drag.startY));
      setEditorOffset({ x, y });
    };
    const up = () => {
      editorDragRef.current = null;
      window.removeEventListener("pointermove", move);
      window.removeEventListener("pointerup", up);
    };
    window.addEventListener("pointermove", move);
    window.addEventListener("pointerup", up, { once: true });
  }, [editorOffset.x, editorOffset.y, readOnly]);

  const selectFirst = useCallback((next: ModelSpec) => {
    setSelectedId(firstComponentId(next));
  }, [setSelectedId]);

  const setAddDefinition = useCallback((bucket: BuilderBucket, functionType: string) => {
    setSelectedDefinitions((current) => ({ ...current, [bucket]: functionType }));
  }, [setSelectedDefinitions]);

  const addAt = useCallback((placement: AddPlacement) => {
    if (readOnly || disabled) return;
    const bucket = placement.bucket;
    const definitions = definitionsForBucket(registry, bucket);
    const definition = placement.functionType
      ? definitions.find((item) => item.function_type === placement.functionType)
      : addableDefinitionForBucket(model, definitions, bucket, selectedDefinitions[bucket]);
    if (!definition) return;
    const pending = buildPendingComponent(model, bucket, definition, addPolarityFor(model, bucket, definition));
    const pathId = placement.mode === "parallel"
      ? `path:${pending.id}`
      : (placement.pathId ?? (bucket === "main" ? "path:main" : `path:${pending.id}`));
    const insertIndex = placement.mode === "parallel" ? 0 : (placement.insertIndex ?? 0);
    const prepared = withPathMetadata(pending, pathId, insertIndex);
    const shifted = normalizePathOrders(model, pathId, insertIndex);
    const next = {
      ...shifted,
      [prepared.location]: [...shifted[prepared.location], prepared],
    } as ModelSpec;
    onChange(next);
    setSelectedId(prepared.id);
  }, [disabled, model, onChange, readOnly, registry, selectedDefinitions, setSelectedId]);

  const addFrom = useCallback((bucket: BuilderBucket, functionType?: string) => {
    addAt({ bucket, functionType, mode: bucket === "main" ? "serial" : "parallel", pathId: bucket === "main" ? "path:main" : undefined });
  }, [addAt]);

  const addLocalParallelById = useCallback((componentId: string) => {
    if (readOnly || disabled) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    addAt({ bucket: "branches", mode: "parallel" });
  }, [addAt, disabled, model, readOnly]);

  const removeById = useCallback((componentId: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const next = removeComponent(model, ref.location, ref.comp.id);
    onChange(next);
    setSelectedId(firstComponentId(next));
  }, [disabled, model, onChange, readOnly, setSelectedId]);

  const renameById = useCallback((componentId: string, nextName: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    const cleanName = nextName.trim();
    if (!ref || !cleanName) return;
    const nextComponent = applyNicknameToParams(ref.comp, cleanName);
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const replaceDefinitionById = useCallback((componentId: string, functionType: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const bucket = ref.comp.location === "series" ? "main" : "branches";
    const definition = definitionsForBucket(registry, bucket).find((item) => item.function_type === functionType);
    if (!definition) return;
    const replacement = createComponentInLocation(definition, ref.location, addPolarityFor(model, bucket, definition));
    const prevNick = typeof ref.comp.metadata?.nickname === "string" ? ref.comp.metadata.nickname : null;
    const switchingToCustom = definition.function_type === "custom" || definition.law_id === "custom_expression";
    const nick = switchingToCustom && looksAutoGeneratedName(ref.comp.id, prevNick)
      ? defaultCustomNicknameFor(bucket)
      : (prevNick ?? ref.comp.id);
    const renamed = applyCustomExpressionParameterUnits(applyNicknameToParams({
      ...replacement,
      id: ref.comp.id,
      location: ref.location,
      metadata: { ...(replacement.metadata ?? {}), pathId: ref.comp.metadata?.pathId, pathOrder: ref.comp.metadata?.pathOrder, nickname: nick },
    }, nick));
    onChange(updateComponent(model, ref.location, ref.comp.id, renamed));
  }, [disabled, model, onChange, readOnly, registry]);

  const updateExpressionById = useCallback((componentId: string, expression: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const nextComponent = applyCustomExpressionParameterUnits({
      ...ref.comp,
      metadata: { ...(ref.comp.metadata ?? {}), expression, expressionSource: "user" },
    }, expression);
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const updateBehaviorById = useCallback((componentId: string, behavior: ComponentBehaviorMode) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const expression = typeof ref.comp.metadata?.expression === "string" && ref.comp.metadata.expression.trim()
      ? ref.comp.metadata.expression
      : defaultExpressionForBehavior(behavior);
    const params = Object.keys(ref.comp.params).length ? ref.comp.params : { R0: defaultParameterFor("R0") };
    const nextComponent = applyCustomExpressionParameterUnits({
      ...ref.comp,
      function_type: "custom",
      law_id: "custom_expression",
      evaluation_form: behavior === "dV_of_I" ? "voltage_drop" : "current_branch",
      placement: ref.location === "series" ? "series_voltage_drop" : "parallel_current_branch",
      metadata: { ...(ref.comp.metadata ?? {}), behavior, expression, expressionSource: "user" },
      params,
    }, expression);
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const addCustomParameterById = useCallback((componentId: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    let index = Object.keys(ref.comp.params).length + 1;
    let name = `P${index}`;
    while (ref.comp.params[name]) {
      index += 1;
      name = `P${index}`;
    }
    const nextComponent = {
      ...ref.comp,
      params: { ...ref.comp.params, [name]: defaultParameterFor(name) },
    };
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const updateCustomParameterById = useCallback((componentId: string, paramName: string, patch: CustomParameterPatch) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref || !ref.comp.params[paramName]) return;
    const nextName = patch.nextName?.trim();
    const paramPatch = parameterFromPatch(patch);
    const nextParams = { ...ref.comp.params };
    const updated = { ...nextParams[paramName], ...paramPatch };
    if (nextName && nextName !== paramName && !nextParams[nextName]) {
      delete nextParams[paramName];
      nextParams[nextName] = { ...updated, label: nextName };
    } else {
      nextParams[paramName] = updated;
    }
    onChange(updateComponent(model, ref.location, ref.comp.id, { ...ref.comp, params: nextParams }));
  }, [disabled, model, onChange, readOnly]);

  const removeCustomParameterById = useCallback((componentId: string, paramName: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref || !ref.comp.params[paramName]) return;
    const nextParams = { ...ref.comp.params };
    delete nextParams[paramName];
    onChange(updateComponent(model, ref.location, ref.comp.id, { ...ref.comp, params: nextParams }));
  }, [disabled, model, onChange, readOnly]);

  const updatePolarityById = useCallback((componentId: string, polarity: string) => {
    if (disabled || readOnly) return;
    const ref = findComponentRef(model, componentId);
    if (!ref) return;
    const nextComponent = {
      ...ref.comp,
      polarity: polarity as "forward" | "reverse" | "symmetric" | null,
    };
    onChange(updateComponent(model, ref.location, ref.comp.id, nextComponent));
  }, [disabled, model, onChange, readOnly]);

  const fallbackGraph = useMemo(() => buildFlowGraph(model, selectedId, language, {
    readOnly,
    disabled,
    registry,
  }), [model, selectedId, language, readOnly, disabled, registry]);
  const [graph, setGraph] = useState(fallbackGraph);

  useEffect(() => {
    let cancelled = false;
    setGraph(fallbackGraph);
    buildFlowGraphWithElk(model, selectedId, language, { readOnly, disabled, registry }).then((nextGraph) => {
      if (!cancelled) setGraph(nextGraph);
    });
    return () => {
      cancelled = true;
    };
  }, [fallbackGraph, model, selectedId, language, readOnly, disabled, registry]);

  useEffect(() => {
    const timer = window.setTimeout(() => {
      fitView({ padding: readOnly ? 0.22 : 0.22, duration: 180, maxZoom: readOnly ? 1.0 : 1.08 });
    }, readOnly ? 90 : 120);
    return () => window.clearTimeout(timer);
  }, [fitView, graph.nodes.length, graph.edges.length, readOnly]);

  const contextValue = useMemo<ModelFlowContextValue>(() => ({
    model,
    registry,
    language,
    disabled,
    readOnly,
    selectedDefinitions,
    removeById,
    addFrom,
    addAt,
    addLocalParallelById,
    setAddDefinition,
    renameById,
    replaceDefinitionById,
    updateExpressionById,
    updateBehaviorById,
    updatePolarityById,
    addCustomParameterById,
    updateCustomParameterById,
    removeCustomParameterById,
  }), [addFrom, addAt, addLocalParallelById, disabled, language, model, readOnly, registry, removeById, renameById, replaceDefinitionById, updateExpressionById, updateBehaviorById, updatePolarityById, addCustomParameterById, updateCustomParameterById, removeCustomParameterById, selectedDefinitions, setAddDefinition]);

  return <ModelFlowContextProvider value={contextValue}>
    <div className={`xy-model-workspace ${readOnly ? "xy-model-readonly" : ""}`} data-testid="equivalent-circuit-canvas">
      <div className="xy-model-flow-shell">
        <ReactFlow
          nodes={graph.nodes}
          edges={graph.edges}
          nodeTypes={nodeTypes}
          edgeTypes={edgeTypes}
          defaultEdgeOptions={{ type: "circuitButton", style: { strokeWidth: 2.4, stroke: "#111827" } }}
          fitView={readOnly}
          fitViewOptions={{ padding: 0.22, maxZoom: 1.0 }}
          defaultViewport={readOnly ? undefined : { x: 140, y: 80, zoom: 1 }}
          minZoom={readOnly ? 0.45 : 0.45}
          maxZoom={readOnly ? 1.4 : 2.4}
          nodesDraggable={false}
          nodesConnectable={false}
          edgesFocusable={false}
          edgesReconnectable={false}
          deleteKeyCode={null}
          connectOnClick={false}
          panOnScroll={false}
          zoomOnScroll={!readOnly}
          zoomOnPinch={!readOnly}
          zoomOnDoubleClick={!readOnly}
          attributionPosition="bottom-left"
          proOptions={{ hideAttribution: true }}
          onNodeClick={(_, node) => {
            if (readOnly) return;
            const refItem = node.data.refItem;
            if (refItem) setSelectedId(refItem.comp.id);
          }}
          onPaneClick={() => {
            if (!readOnly) setSelectedId(null);
          }}
        >
          <Background gap={24} size={1.4} />
          {!readOnly ? <Controls showInteractive={false} /> : null}
          {!readOnly ? <Panel position="top-left" className="xy-canvas-preset-panel">
            <ModelPresetControls model={model} language={language} onChange={onChange} disabled={disabled} onAfterPreset={selectFirst} onGoToFitting={onGoToFitting} />
            {canvasActions ? <div className="xy-canvas-synthetic-tool">{canvasActions}</div> : null}
          </Panel> : null}
          {!readOnly && selectedId ? <Panel position="top-right" className="xy-canvas-editor-panel">
            <div className="xy-draggable-editor-shell" style={{ transform: `translate(${editorOffset.x}px, ${editorOffset.y}px)` }}>
              <ComponentCanvasEditor selectedId={selectedId} onHeaderPointerDown={beginEditorDrag} />
            </div>
          </Panel> : null}

        </ReactFlow>
      </div>
    </div>
  </ModelFlowContextProvider>;
}
